import { Product } from './types';

export const PRODUCTS: Product[] = [
  // WIKSTEA PRODUCTS
  {
    id: 'w1',
    name: 'Teh Gaharu Original',
    category: 'Wikstea Product',
    price: 85000,
    description: 'Teh herbal alami dari daun gaharu dengan rasa bold, aroma khas, dan warna kemerahan. Kaya antioksidan untuk membantu melawan radikal bebas.',
    image: '/images/source/Teh Gaharu Original.jpg',
    origin: 'Indonesia',
    steepTime: '3-5 mins',
    temperature: '90°C',
    stock: 25,
    rating: 4.8,
    reviewCount: 68
  },
  {
    id: 'w2',
    name: 'Teh Gaharu Serai',
    category: 'Wikstea Product',
    price: 85000,
    description: 'Perpaduan daun gaharu dan serai dengan aroma segar dan efek menenangkan untuk relaksasi tubuh dan pikiran.',
    image: '/images/source/Teh Gaharu Serai.jpg',
    origin: 'Indonesia',
    steepTime: '3-5 mins',
    temperature: '90°C',
    stock: 18,
    rating: 4.7,
    reviewCount: 42
  },
  {
    id: 'w3',
    name: 'Teh Gaharu Jahe',
    category: 'Wikstea Product',
    price: 85000,
    description: 'Kombinasi gaharu and jahe dengan sensasi hangat, kaya antioksidan dan gingerol untuk meningkatkan daya tahan tubuh serta membantu detoksifikasi.',
    image: '/images/source/Teh Gaharu Jahe.jpg',
    origin: 'Indonesia',
    steepTime: '3-5 mins',
    temperature: '100°C',
    stock: 12,
    rating: 4.9,
    reviewCount: 55
  },
  {
    id: 'w4',
    name: 'Teh Gaharu Kayu Manis',
    category: 'Wikstea Product',
    price: 85000,
    description: 'Minuman herbal dengan perpaduan gaharu dan kayu manis yang membantu menjaga gula darah, metabolisme, dan relaksasi tubuh.',
    image: '/images/source/Teh Gaharu Kayu Manis.jpg',
    origin: 'Indonesia',
    steepTime: '3-5 mins',
    temperature: '90°C',
    stock: 15,
    rating: 4.6,
    reviewCount: 31
  },
  {
    id: 'w5',
    name: 'Roasted Milk Tea',
    category: 'Wikstea Product',
    price: 35000,
    description: 'Campuran susu, gula aren, dan daun gaharu dengan rasa creamy dan aroma menenangkan, cocok untuk waktu santai.',
    image: '/images/source/Roasted Milk tea.jpeg',
    origin: 'Indonesia',
    steepTime: 'Ready to Drink',
    temperature: 'Cold/Hot',
    stock: 30,
    rating: 4.8,
    reviewCount: 89
  },
  // ACANTHACE DRINK PRODUCTS
  {
    id: 'a1',
    name: 'Teh Jeruju Original',
    category: 'Acanthace Drink',
    price: 75000,
    description: 'Minuman teh jeruju alami tanpa pengawet, pewarna, dan pemanis buatan, menggunakan stevia serta memiliki sifat anti-inflamasi.',
    image: '/images/source/Teh Jeruju Original.jpg',
    origin: 'Indonesia',
    steepTime: '4-6 mins',
    temperature: '95°C',
    stock: 22,
    rating: 4.7,
    reviewCount: 47
  },
  {
    id: 'a2',
    name: 'Teh Jeruju Serai',
    category: 'Acanthace Drink',
    price: 75000,
    description: 'Teh jeruju dan serai dengan aroma segar, kaya antioksidan, membantu relaksasi dan detoksifikasi alami.',
    image: '/images/source/Teh Jeruju Serai.jpg',
    origin: 'Indonesia',
    steepTime: '4-6 mins',
    temperature: '95°C',
    stock: 14,
    rating: 4.8,
    reviewCount: 36
  },
  {
    id: 'a3',
    name: 'Teh Jeruju Jahe',
    category: 'Acanthace Drink',
    price: 75000,
    description: 'Perpaduan daun jeruju dan jahe dengan rasa hangat untuk membantu peredaran darah dan menjaga daya tahan tubuh.',
    image: '/images/source/Teh Jeruju Jahe.jpg',
    origin: 'Indonesia',
    steepTime: '4-6 mins',
    temperature: '100°C',
    stock: 10,
    rating: 4.6,
    reviewCount: 28
  },
  {
    id: 'a4',
    name: 'Teh Jeruju Pandan',
    category: 'Acanthace Drink',
    price: 75000,
    description: 'Teh jeruju dengan aroma pandan yang harum dan menenangkan, membantu menjaga keseimbangan tubuh dan relaksasi.',
    image: '/images/source/Teh Jeruju Pandan.jpg',
    origin: 'Indonesia',
    steepTime: '4-6 mins',
    temperature: '95°C',
    stock: 16,
    rating: 4.7,
    reviewCount: 33
  },
  {
    id: 'a5',
    name: 'Teh Jeruju Bunga Telang',
    category: 'Acanthace Drink',
    price: 75000,
    description: 'Kombinasi daun jeruju dan bunga telang dengan warna biru alami, kaya antioksidan dan memberi efek menenangkan.',
    image: '/images/source/Teh Jeruju Bunga Telang.jpg',
    origin: 'Indonesia',
    steepTime: '4-6 mins',
    temperature: '90°C',
    stock: 19,
    rating: 4.9,
    reviewCount: 50
  },
  {
    id: 'a6',
    name: 'Teh Bunga Telang',
    category: 'Acanthace Drink',
    price: 75000,
    description: 'Minuman bunga telang alami tanpa 3P (pengawet, pewarna, pemanis buatan) dengan pemanis stevia.',
    image: '/images/source/Teh bunga telang.jpg',
    origin: 'Indonesia',
    steepTime: '5-7 mins',
    temperature: '85°C',
    stock: 20,
    rating: 4.8,
    reviewCount: 41
  },
  {
    id: 'a7',
    name: 'Cheeru Tea',
    category: 'Acanthace Drink',
    price: 35000,
    description: 'Teh kekinian dari daun jeruju, mint, dan lychee yang menyegarkan sekaligus menenangkan.',
    image: '/images/source/Cheeru tea.jpeg',
    origin: 'Indonesia',
    steepTime: 'Ready to Drink',
    temperature: 'Cold',
    stock: 0,
    rating: 4.5,
    reviewCount: 15
  },
  {
    id: 'a8',
    name: 'Jenny Berry',
    category: 'Acanthace Drink',
    price: 35000,
    description: 'Perpaduan teh jeruju, lemon, strawberry, madu, dan mint dengan rasa segar dan kaya antioksidan.',
    image: '/images/source/Jenny Berry.jpeg',
    origin: 'Indonesia',
    steepTime: 'Ready to Drink',
    temperature: 'Cold',
    stock: 25,
    rating: 4.8,
    reviewCount: 74
  },
  {
    id: 'a9',
    name: 'Butterfly Yogurt',
    category: 'Acanthace Drink',
    price: 40000,
    description: 'Yogurt sehat dengan sirup bunga telang alami dan lemon, memiliki warna biru alami tanpa pewarna buatan.',
    image: '/images/source/Butterfly yogurt.jpeg',
    origin: 'Indonesia',
    steepTime: 'Ready to Drink',
    temperature: 'Cold',
    stock: 28,
    rating: 4.9,
    reviewCount: 92
  },
  // GWI PRODUCTS
  {
    id: 'g1',
    name: 'Madu GW',
    category: 'GWI Product',
    price: 150000,
    description: 'Madu murni dari hutan akasia dengan sifat antimikroba dan kaya nutrisi, cocok sebagai pemanis alami sehat.',
    image: '/images/source/Madu GW.png',
    origin: 'Indonesia',
    steepTime: 'Natural',
    temperature: 'Room Temp',
    stock: 8,
    rating: 5.0,
    reviewCount: 104
  }
];
